"""Is the posterior width the data's limit, or the network's?

A single simulated household's posterior is wide (figure 10). If that width is
genuinely what one household's seven waves can support, then giving the model
MORE data generated by the same theta should shrink it, roughly as
``1 / sqrt(M)`` for M independent households, and keep it centred on the truth.
If instead the network were simply imprecise, extra data would not tighten it
in that orderly way.

The simulator already supplies the experiment: every draw stores 8 independent
households sharing one true theta. Households are independent given theta, so

    p(theta | x_1..x_M)  ∝  prod_i q(theta | x_i) / p(theta)^(M-1)

evaluated on a 3-D grid. The flow lives in u = log(1 - delta), where the uniform
prior on delta has density ∝ exp(u) (the Jacobian of delta = 1 - exp(u)), so the
correction there is ``-(M-1) * u``; beta and rho have flat priors.

Caveat, stated before the result: multiplying M approximate posteriors also
multiplies their approximation errors, so pooled coverage can drift below
nominal as M grows. That is a property of the pooling, not of the data.

Usage::

    uv run python scripts/pooling_check.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch

from hh_npe.data.windows import build_windowed
from hh_npe.npe.prior import PHASE3, log1m_box, sample_sobol, to_log1m
from hh_npe.npe.train import load_posterior
from hh_npe.simulator.laibson_calibration import EDUC_GROUPS
from scripts.compare_windows import educ_by_draw, split_shards

MS = (1, 2, 4, 8)


def grid_logpost(posts, xs: torch.Tensor, grid: torch.Tensor, chunk: int) -> np.ndarray:
    """Sum over households of the ensemble log-density, on the grid (log space)."""
    total = torch.zeros(len(grid), device=grid.device)
    with torch.no_grad():
        for x1 in xs:
            per = []
            for p in posts:
                lp = torch.cat([p.posterior_estimator.log_prob(
                    grid[a:a + chunk, None, :], condition=x1[None])[:, 0]
                    for a in range(0, len(grid), chunk)])
                per.append(lp)
            # Ensemble = equal mixture of members.
            total += torch.logsumexp(torch.stack(per), 0) - np.log(len(posts))
    return total.cpu().numpy()


def summarise(lp: np.ndarray, pts: np.ndarray, truth: np.ndarray) -> dict:
    w = np.exp(lp - lp.max()); w /= w.sum()
    mean = (w[:, None] * pts).sum(0)
    sd = np.sqrt((w[:, None] * (pts - mean) ** 2).sum(0))
    cov = []
    for j in range(3):
        o = np.argsort(pts[:, j]); c = np.cumsum(w[o])
        lo, hi = pts[o, j][np.searchsorted(c, 0.05)], pts[o, j][np.searchsorted(c, 0.95)]
        cov.append(lo <= truth[j] <= hi)
    return {"mean": mean, "sd": sd, "cov": np.array(cov)}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run_dirs", type=Path, nargs="+",
                    default=[Path(f"outputs/adopted/log1m_s{s}") for s in range(5)])
    ap.add_argument("--shards", type=Path,
                    default=Path("data/processed/phase4_educ_dataset_shards"))
    ap.add_argument("--n_draws", type=int, default=60)
    ap.add_argument("--grid", type=int, default=44)
    ap.add_argument("--chunk", type=int, default=16384)
    ap.add_argument("--out", type=Path, default=Path("outputs/pooling_check.json"))
    args = ap.parse_args()

    sh = sorted(args.shards.glob("shard_*.npz"))
    _t, held = split_shards(sh, 57344)
    th, x, pid = build_windowed(held, sample_sobol(65536, PHASE3, seed=0), k=1,
                                n_waves=7, seed=999, start_low=24, start_high=45,
                                wave_years=2, with_age=True)
    c = educ_by_draw(sh)[pid.numpy()] == EDUC_GROUPS.index("comphs")
    th, x, pid = th[c].numpy(), x[c], pid[c].numpy()
    draws = [d for d in np.unique(pid) if (pid == d).sum() == 8][: args.n_draws]
    print(f"{len(draws)} held-out comphs draws, 8 households each sharing theta")

    posts = [load_posterior(r / "posterior_7w.pt")["posterior"] for r in args.run_dirs]
    dev = next(posts[0].posterior_estimator.parameters()).device
    box = log1m_box(PHASE3)
    names = PHASE3.names
    rows = {m: [] for m in MS}
    torch.set_grad_enabled(False)
    for k, d in enumerate(draws):
        idx = np.flatnonzero(pid == d)
        truth = th[idx[0]]
        xs = x[idx].to(dev)
        # Grid bounds: generous box around every single-household posterior,
        # so the pooled posterior (which is narrower) lies well inside.
        g1 = []
        for i in range(8):
            s = torch.cat([p.posterior_estimator.sample((300,), condition=xs[i:i + 1])[:, 0]
                           for p in posts]).cpu().numpy()
            s = s[((s >= box.low) & (s <= box.high)).all(1)]
            g1.append(np.percentile(s, [0.5, 99.5], axis=0))
        g1 = np.array(g1)
        lo = np.maximum(g1[:, 0].min(0), box.low); hi = np.minimum(g1[:, 1].max(0), box.high)
        axes = [np.linspace(lo[j], hi[j], args.grid) for j in range(3)]
        pts_u = np.stack(np.meshgrid(*axes, indexing="ij"), -1).reshape(-1, 3)
        grid = torch.as_tensor(pts_u, dtype=torch.float32, device=dev)
        pts = pts_u.copy(); pts[:, 1] = 1 - np.exp(pts_u[:, 1])     # to delta space
        cell_w = np.ones(len(pts_u))  # uniform grid in u; mass per cell handled by density in u
        acc = np.zeros(len(pts_u))
        for m_i, i in enumerate(range(8), start=1):
            acc += grid_logpost(posts, xs[i:i + 1], grid, args.chunk)
            if m_i in MS:
                # prior correction in u-space: p(u) ∝ exp(u)
                lp = acc - (m_i - 1) * pts_u[:, 1] + np.log(cell_w)
                rows[m_i].append({**summarise(lp, pts, truth), "truth": truth})
        print(f"  draw {k + 1}/{len(draws)}", flush=True)

    print(f"\n{'M':>3s}" + "".join(f"{n + ' sd':>11s}" for n in names)
          + "".join(f"{n + ' |err|':>12s}" for n in names)
          + "".join(f"{n + ' cov90':>11s}" for n in names))
    out = {}
    base = None
    for m in MS:
        r = rows[m]
        sd = np.median([q["sd"] for q in r], 0)
        err = np.median([np.abs(q["mean"] - q["truth"]) for q in r], 0)
        cov = np.mean([q["cov"] for q in r], 0)
        base = sd if base is None else base
        print(f"{m:3d}" + "".join(f"{v:11.4f}" for v in sd)
              + "".join(f"{v:12.4f}" for v in err) + "".join(f"{v:11.2f}" for v in cov))
        out[m] = {"median_sd": sd.tolist(), "median_abs_err": err.tolist(),
                  "coverage_90": cov.tolist()}
    print("\nsd relative to M=1, and the 1/sqrt(M) it would follow if the width is the data's:")
    for m in MS:
        rel = np.array(out[m]["median_sd"]) / base
        print(f"  M={m}: " + "  ".join(f"{n} {v:.2f}" for n, v in zip(names, rel))
              + f"   (1/sqrt(M) = {1 / np.sqrt(m):.2f})")
    args.out.write_text(json.dumps({"n_draws": len(draws), "by_M": out}, indent=2))
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
