"""Fresh SBC set for option A through the training code path (RESULTS.md 38).

The first SBC set (``outputs/optionA/sbc_sims.pt``, one household per draw)
puts truths above beta's 95th percentile 11.4% of the time where the posterior
mean is in [0.8, 0.95); the held-out training-sequence draws, reweighted to the
uniform prior, put them there 4.9% of the time (§37.3). This set settles it:
1,024 uniform-prior draws generated by ``generate_dataset.py`` with every
training setting (``scripts/run_sbc16.sh``), 16 households each, so the tail
rate rests on ~16x the households.

Each household is scored on its own posterior (the importance-weighted,
uniform-prior posterior SBC always checks). Rates and coverage use all
households, with a bootstrap over blocks of 16 draws (shared R_gamma and card
type, and 16 households per draw); KS p-values use one household per draw (one
per block for R_gamma), so their ranks are independent.

Usage::

    PYTHONPATH=. .venv/bin/python scripts/sbc_households.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch
from scipy import stats

from hh_npe.evaluation.weighted import sample_weighted
from hh_npe.npe.prior import PHASE3, sample_sobol
from scripts.optionA import (
    BOX,
    CUTS,
    SBC_SEED,
    SHARDS,
    _weighting,
    flow_box,
    load_members,
    one_per_draw,
    windows,
)
from scripts.tail_diagnostic import BLOCK, _boot_counts, rate

SBC16 = Path("data/processed/optionA_sbc16_shards")
ARMS = {"linear": "outputs/optionA", "log1m": "outputs/optionA_beta_log1m",
        "logit": "outputs/optionA_beta_logit"}
#: Settings that must equal the training generation's for SBC to test the
#: training generative process (the rest: seed, proposal, notes).
SAME = ("simulator", "grid", "device", "gpu", "theta_batch", "chunk", "start_age",
        "n_waves", "wave_years", "store_panel", "n_households", "educ",
        "card_types", "rgamma_range")
LABEL = {"beta": r"$\beta$", "delta": r"$\delta$", "crra": r"$\rho$",
         "R_gamma": r"$R_\gamma$"}
#: Earlier estimates of the beta tail rate, for the comparison line.
EARLIER = {"first SBC set (1 hh per draw)": (0.114, 0.079, 0.150),
           "held-out, reweighted (§37.3)": (0.049, 0.029, 0.072)}


def load_sbc_shards(shards: Path, train_shards: Path = SHARDS):
    """theta per draw and the shard files, after checking that the set was
    generated as training was, from the uniform prior."""
    cfg = json.loads((shards / "solver_config.json").read_text())
    ref = json.loads((train_shards / "solver_config.json").read_text())
    diff = {k: (cfg.get(k), ref.get(k)) for k in SAME if cfg.get(k) != ref.get(k)}
    if diff or cfg.get("proposal") != "uniform":
        raise SystemExit(f"{shards}: not generated as training was, from the uniform "
                         f"prior: {diff or cfg.get('proposal')}")
    meta = []
    for f in sorted(shards.glob("shard_*.npz")):
        d = np.load(f)
        meta.append((int(d["lo"]), int(d["hi"]), d["theta"], f))
    meta.sort(key=lambda t: t[0])
    if not meta or [m[0] for m in meta] != [0] + [m[1] for m in meta[:-1]]:
        raise SystemExit(f"{shards}: shards do not tile a contiguous range from 0")
    theta = np.concatenate([m[2] for m in meta])
    n = len(theta)
    if not np.allclose(theta[:, :3], sample_sobol(n, PHASE3, seed=cfg["seed"]),
                       rtol=0, atol=1e-12):
        raise SystemExit(f"{shards}: theta is not the uniform Sobol sequence")
    blocks = theta[:, 3].reshape(-1, BLOCK) if n % BLOCK == 0 else None
    if blocks is None or not (blocks == blocks[:, :1]).all():
        raise SystemExit(f"{shards}: R_gamma is not constant within blocks of {BLOCK}")
    return theta, [m[3] for m in meta], cfg


def score(r: dict, th: np.ndarray, pid: np.ndarray, one: np.ndarray) -> dict:
    ok = np.isfinite(r["u"]).all(1)
    u, mean, blk = r["u"], r["mean"], pid // BLOCK
    counts, b = _boot_counts(blk[ok])
    w = np.ones(ok.sum())
    inside = lambda uj: (uj >= 0.05) & (uj <= 0.95)
    out = {"n_households": int(ok.sum()), "n_draws": int(len(np.unique(pid[ok]))),
           "coverage_90": {}, "ks_p_one_per_draw": {}, "by_posterior_mean": {}}
    for j, n in enumerate(BOX.names):
        uj = u[ok, j]
        out["coverage_90"][n] = rate(inside(uj), np.ones(len(uj), bool), w, counts, b)
        if n == "R_gamma":   # one draw per block: R_gamma is shared within a block
            pick = ok & one & (pid % BLOCK == 0)
        else:
            pick = ok & one
        out["ks_p_one_per_draw"][n] = float(stats.kstest(u[pick, j], "uniform").pvalue)
        c, rows = CUTS[n], []
        for a, hi in zip(c[:-1], c[1:]):
            m = (mean[ok, j] >= a) & ((mean[ok, j] < hi) if hi < c[-1] else (mean[ok, j] <= hi))
            row = {"lo": a, "hi": hi, "n": int(m.sum()),
                   "n_draws": int(len(np.unique(pid[ok][m])))}
            if m.sum() >= 20:
                for k, hit in (("coverage_90", inside(uj)), ("above_95", uj > 0.95),
                               ("below_5", uj < 0.05)):
                    row[k] = rate(hit, m, w, counts, b)
            rows.append(row)
        out["by_posterior_mean"][n] = rows
    top = th[ok, 0] >= 0.95
    out["coverage_true_beta_ge_095"] = rate(inside(u[ok, 0]), top, w, counts, b)
    out["coverage_true_beta_ge_095"]["n"] = int(top.sum())
    return out


def verdict(s: dict) -> str:
    """The reading fixed before the run (RESULTS.md 38)."""
    reg = next(r for r in s["by_posterior_mean"]["beta"] if r["lo"] == 0.8)["above_95"]
    lo, hi = reg["ci90"]
    if reg["rate"] <= 0.075 and lo <= 0.05:
        return "calibrated: the first set's excess was chance"
    if reg["rate"] >= 0.075 and lo > 0.05:
        return "defect confirmed: the held-out diagnostic missed it"
    return "inconclusive: a mild excess"


def show(res: dict) -> None:
    f = lambda d: f"{d['rate']:.3f} ({d['ci90'][0]:.3f}-{d['ci90'][1]:.3f})"
    for arm, s in res["arms"].items():
        print(f"\n=== {arm}: {s['n_households']} households from {s['n_draws']} draws ===")
        print(f"{'':10s}{'coverage (90% CI)':>26s}{'KS p, 1 per draw':>18s}")
        for n in BOX.names:
            print(f"{n:10s}{f(s['coverage_90'][n]):>26s}{s['ks_p_one_per_draw'][n]:18.3f}")
        print("by posterior-mean region: coverage / above 95th / below 5th")
        for n in BOX.names:
            for r in s["by_posterior_mean"][n]:
                if "coverage_90" not in r:
                    print(f"  {n:8s}[{r['lo']:g}, {r['hi']:g})  n={r['n']}")
                    continue
                print(f"  {n:8s}[{r['lo']:g}, {r['hi']:g})  n={r['n']:5d} ({r['n_draws']:4d} draws)"
                      f"  {r['coverage_90']['rate']:.3f}  {f(r['above_95'])}  {f(r['below_5'])}")
        t = s["coverage_true_beta_ge_095"]
        print(f"coverage, true beta >= 0.95 (n={t['n']}): {f(t)}")
        print(f"beta tail verdict: {s['verdict']}")
    print("\nbeta, truth above the 95th percentile where the posterior mean is in [0.8, 0.95):")
    for k, (r, lo, hi) in EARLIER.items():
        print(f"  {k:34s}{r:.3f} ({lo:.3f}-{hi:.3f})")
    for arm, s in res["arms"].items():
        reg = next(r for r in s["by_posterior_mean"]["beta"] if r["lo"] == 0.8)
        print(f"  {'fresh set, ' + arm:34s}{f(reg['above_95'])}  n={reg['n']}")


def figure(res: dict, u_lin: np.ndarray, one: np.ndarray, path: Path) -> None:
    """ECDF of the ranks minus the uniform, per parameter, one household per
    draw, with the old SBC set; the band is the KS 95% band for its n."""
    import matplotlib.pyplot as plt

    old = np.load("outputs/optionA/evaluation/sbc_ensemble.npz")["u"]
    grid = np.linspace(0, 1, 201)
    fig, axs = plt.subplots(1, 4, figsize=(15, 3.6), sharey=True)
    for j, (ax, n) in enumerate(zip(axs, BOX.names)):
        for lab, uu, col in (("fresh set, 1 household per draw", u_lin[one, j], "#1f77b4"),
                             ("first SBC set", old[:, j], "#d62728")):
            uu = uu[np.isfinite(uu)]
            ax.plot(grid, (uu[:, None] <= grid).mean(0) - grid, color=col, label=lab)
        band = 1.358 / np.sqrt(one.sum())
        ax.fill_between(grid, -band, band, color="0.85", label="KS 95% band (fresh)")
        ax.axhline(0, color="0.4", lw=0.8)
        ax.set_title(LABEL[n])
        ax.set_xlabel("rank u")
    axs[0].set_ylabel("ECDF(u) - u")
    axs[0].legend(fontsize=8, loc="lower left")
    fig.suptitle("Option A (linear beta): SBC rank calibration, fresh set against the "
                 "first; R_gamma ranks are shared within blocks of 16 draws")
    fig.tight_layout()
    fig.savefig(path, dpi=130)
    plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--shards", type=Path, default=SBC16)
    ap.add_argument("--arms", nargs="+", default=list(ARMS), choices=list(ARMS))
    ap.add_argument("--n_draws", type=int, default=2000)
    ap.add_argument("--device", default="cuda" if torch.cuda.is_available() else None)
    ap.add_argument("--out", type=Path, default=Path("outputs/sbc16"))
    ap.add_argument("--figure", type=Path, default=Path("figures/34_sbc16_calibration.png"))
    args = ap.parse_args()

    theta_all, files, cfg = load_sbc_shards(args.shards)
    th, x, pid, _f = windows(files, theta_all, seed=SBC_SEED)
    th, pid = th.numpy().astype(float), pid.numpy()
    one = np.zeros(len(pid), bool)
    one[one_per_draw(torch.from_numpy(pid), seed=0)] = True
    print(f"{len(th)} households from {len(np.unique(pid))} draws "
          f"(seed {cfg['seed']}, {len(files)} shards)", flush=True)

    args.out.mkdir(parents=True, exist_ok=True)
    res = {"shards": str(args.shards), "seed": cfg["seed"], "arms": {}}
    u_lin = None
    for arm in args.arms:
        members, proposal, mcfg = load_members(
            [Path(ARMS[arm]) / f"s{s}" for s in range(5)], args.device)
        bt = mcfg["beta_transform"]
        inv, lw = _weighting(proposal, bt)
        fb = flow_box(bt)
        torch.manual_seed(0)
        r = sample_weighted(members, x, args.n_draws, fb.low, fb.high, invert=inv,
                            log_weight=lw, truth=th)
        s = score(r, th, pid, one)
        s["verdict"] = verdict(s)
        res["arms"][arm] = s
        np.savez(args.out / f"sbc16_{arm}.npz", truth=th, pid=pid, one_per_draw=one,
                 **{k: r[k] for k in ("mean", "sd", "lo", "hi", "u", "ess")})
        if arm == "linear":
            u_lin = r["u"]
        print(f"  {arm} done", flush=True)
        del members
        torch.cuda.empty_cache()

    (args.out / "sbc16.json").write_text(json.dumps(res, indent=2))
    show(res)
    if u_lin is not None:
        figure(res, u_lin, one & np.isfinite(u_lin).all(1), args.figure)
        print(f"\nwrote {args.out}/ and {args.figure}")


if __name__ == "__main__":
    main()
